# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: datalab@tuwien.ac.at
author_name: Florian Jaeger
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: server
labextension_name: grader-labextension
mimetype: ''
mimetype_name: ''
project_short_description: Grader Labextension is a JupyterLab extension to enable
    automatic grading of assignment notebooks.
python_name: grader_labextension
repository: https://github.com/TU-Wien-dataLAB/Grader-Labextension
test: true
viewer_name: ''

