/**
 * Grader Extension API Schemas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AutoStatus = {
    NotGraded: 'not_graded',
    Pending: 'pending',
    AutomaticallyGraded: 'automatically_graded',
    GradingFailed: 'grading_failed'
} as const;
export type AutoStatus = typeof AutoStatus[keyof typeof AutoStatus];

