/**
 * Grader Extension API Schemas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FeedbackStatus = {
    NotGenerated: 'not_generated',
    Generating: 'generating',
    Generated: 'generated',
    GenerationFailed: 'generation_failed',
    FeedbackOutdated: 'feedback_outdated'
} as const;
export type FeedbackStatus = typeof FeedbackStatus[keyof typeof FeedbackStatus];

