/**
 * Grader Extension API Schemas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ManualStatus = {
    NotGraded: 'not_graded',
    ManuallyGraded: 'manually_graded',
    BeingEdited: 'being_edited'
} as const;
export type ManualStatus = typeof ManualStatus[keyof typeof ManualStatus];

