# a mybinder.org-ready environment for demoing grader_labextension
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate grader-labextension-demo
#
name: grader-labextension-demo

channels:
  - conda-forge
  - nodefaults
dependencies:
  # !! you can only use single `=` to set a version. Otherwise it will break the update job
  - invoke=2.2.0
  - packaging
  - pyyaml
  # applications
  - jupyterlab=4.0.6
  - jupyter-collaboration=1.0.1
  - nbconvert=7.6.0
  - notebook==7.0.4
  # extensions
  - jupyter-offlinenotebook=0.2.2
  - jupyterlab-fasta=3.3
  - jupyterlab-geojson=3.4
  # Python Kernel
  - ipykernel=6.24.0
  - ipywidgets=8
  - ipyleaflet=0.17.3
  - altair=5.0.1
  - bqplot=0.12.40
  - matplotlib-base=3.7.1
  - pandas=2.0.3
  - python=3.11
  - scikit-image=0.21.0
  - scikit-learn=1.3.0
  - seaborn-base=0.12.2
  - traittypes=0.2.1
  # CLI tools
  - pip
  - vim
  - git
  - sqlite
  - pip:
      - grader-service==0.5.1
      - grader-labextension==0.7.0
      