name: "Project Management Issue Creation Actions"

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  send_issue_to_management_tool:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
          NUMBER: ${{ github.event.issue.number }}
          URL: ${{ github.event.issue.html_url }}
        run: |
          echo "Issue title: $TITLE"
          echo "Issue body: $BODY"
          echo "Issue number: $NUMBER"
          echo "Issue url: $URL"

      - name: Send issue to GitLab CI
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
        run: |
          curl -X POST --fail \
               -F token=${{ secrets.GITLAB_CI_TRIGGER_TOKEN }} \
               -F "ref=main" \
               -F "variables[ACTION]=OPEN" \
               -F "variables[TITLE]=$TITLE" \
               -F "variables[DESCRIPTION]=$BODY" \
               -F "variables[URL]=$URL" \
               -F "variables[SOURCE]=github" \
               ${{ secrets.GITLAB_CI_TRIGGER_URL }}
